# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be239c3265a08853c5c765b0463e63b40c7a85a32a4bce885c92db4aaf06849cd516d74e38d5a88ce9a58460c8451861f8ac1ae2c4efe026446b8a7763ee5285

test:
  secret_key_base: 1727eae0f117c4d3a031ec422ecb3af9057a89585d734ef566cd5b76c033f2319e163542b3339fd67305fcb40dbe8ea96e5c08ea4520eab35448d9d9ba5e5fa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
